apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-loki-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  claimRef:
    namespace: loki
    name: storage-loki-0
  hostPath:
    path: '/mnt/data/loki'
    type: DirectoryOrCreate
