apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-stock-server
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentgateway-demo
    agentgateway.dev/feature: mcp-server
    account: mcp-stock-server
