apiVersion: v1
kind: Service
metadata:
  name: mcp-stock-server
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentgateway-demo
    agentgateway.dev/feature: mcp-server
    app: mcp-stock-server
spec:
  selector:
    app: mcp-stock-server
  ports:
    - port: 80
      targetPort: 8000
      appProtocol: kgateway.dev/mcp
  type: ClusterIP
