apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayParameters
metadata:
  name: agentgateway-custom-params
  namespace: agentgateway-system
spec:
  kube:
    agentgateway:
      customConfigMapName: agentgateway-custom-config
